services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: solidarity-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Esperanca@Solidaria2026
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - esperanca-solidaria-network

  # api:
  #   build:
  #     context: ./src
  #     dockerfile: web/EsperancaSolidaria.API/Dockerfile
  #   container_name: solidarity-api
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EsperancaSolidaria;User Id=sa;Password=Esperanca@Solidaria2026;TrustServerCertificate=True;MultipleActiveResultSets=true
  #   depends_on:
  #     - sqlserver
  #   networks:
  #     - esperanca-solidaria-network

volumes:
  sqlserver_data:

networks:
  esperanca-solidaria-network:
    driver: bridge