apiVersion: v1
kind: Secret
metadata:
  name: esperanca-solidaria-api-secret
type: Opaque
data:
  ConnectionStrings__EsperancaSolidaria: U2VydmVyPXNxbHNlcnZlci1zZXJ2aWNlLDE0MzM7RGF0YWJhc2U9RXNwZXJhbmNhU29saWRhcmlhO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9RXNwZXJhbmNhQFByb2QyMDI2O1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZQ==
  JwtSettings__SecretKey: c0VaRVk3M2NxbklKT0FGNWlibkpLMENvMHhQR0xNczBIdTZtblE0a2RYeQ==
  JwtSettings__Issuer: RXNwZXJhbmNhU29saWRhcmlhLkFQSQ==
  JwtSettings__Audience: RXNwZXJhbmNhU29saWRhcmlhLkFQSQ==
  SeedAdmin__Email: Z2VzdG9yZXNwZXJhbmNhc29saWRhcmlhQGdtYWlsLmNvbQ==
  SeedAdmin__Password: RXNwZXJhbmNhQEdlc3RvcjIwMjY=
  RabbitMqOptions__HostName: cmFiYml0bXEtc2VydmljZQ==
  RabbitMqOptions__UserName: ZXNwZXJhbmNhc29saWRhcmlh
  RabbitMqOptions__Password: RXNwZXJhbmNhQFByb2QyMDI2
  MongoDb__ConnectionString: bW9uZ29kYjovL3Jvb3Q6RXNwZXJhbmNhI1Byb2QyMDI2QG1vbmdvZGItc2VydmljZToyNzAxNy8/YXV0aFNvdXJjZT1hZG1pbg==
  MongoDb__DatabaseName: ZXNwZXJhbmNhLXNvbGlkYXJpYS1ldmVudHM=
  Observability__LokiUrl: aHR0cDovL2xva2kubW9uaXRvcmluZy5zdmMuY2x1c3Rlci5sb2NhbDozMTAw
  Observability__TempoOtlpEndpoint: aHR0cDovL3RlbXBvLm1vbml0b3Jpbmcuc3ZjLmNsdXN0ZXIubG9jYWw6NDMxNw==

#ConnectionStrings__EsperancaSolidaria: Server=sqlserver-service,1433;Database=EsperancaSolidaria;User Id=sa;Password=Esperanca@Prod2026;TrustServerCertificate=True;MultipleActiveResultSets=true
# JwtSettings__SecretKey: sEZEY73cqnIJOAF5ibnJK0Co0xPGLMs0Hu6mnQ4kdXy
# JwtSettings__Issuer: EsperancaSolidaria.API
# JwtSettings__Audience: EsperancaSolidaria.API
# SeedAdmin__Email: gestoresperancasolidaria@gmail.com
# SeedAdmin__Password: Esperanca@Gestor2026
# RabbitMqOptions__HostName: rabbitmq-service
# RabbitMqOptions__UserName: esperancasolidaria
# RabbitMqOptions__Password: Esperanca@Prod2026
# MongoDb__ConnectionString: mongodb://root:Esperanca#Prod2026@mongodb-service:27017/?authSource=admin
# MongoDb__DatabaseName: esperanca-solidaria-events
# Observability__LokiUrl: http://loki.monitoring.svc.cluster.local:3100
# Observability__TempoOtlpEndpoint: http://tempo.monitoring.svc.cluster.local:4317
