apiVersion: v1
kind: Secret
metadata:
  name: esperanca-solidaria-worker-doacao-realizada-secret
type: Opaque
data:
  ConnectionStrings__EsperancaSolidaria: U2VydmVyPXNxbHNlcnZlci1zZXJ2aWNlLDE0MzM7RGF0YWJhc2U9RXNwZXJhbmNhU29saWRhcmlhO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9RXNwZXJhbmNhQFByb2QyMDI2O1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZQ==
  RabbitMqOptions__HostName: cmFiYml0bXEtc2VydmljZQ==
  RabbitMqOptions__UserName: ZXNwZXJhbmNhc29saWRhcmlh
  RabbitMqOptions__Password: RXNwZXJhbmNhQFByb2QyMDI2

#ConnectionStrings__EsperancaSolidaria: Server=sqlserver-service,1433;Database=EsperancaSolidaria;User Id=sa;Password=Esperanca@Prod2026;TrustServerCertificate=True;MultipleActiveResultSets=true
# RabbitMqOptions__HostName: rabbitmq-service
# RabbitMqOptions__UserName: esperancasolidaria
# RabbitMqOptions__Password: Esperanca@Prod2026

