name: Pipeline CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - id: set_tag
        name: Define Image Tag
        run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build Docker Image API
        run: docker build -f ./src/web/EsperancaSolidaria.API/Dockerfile -t esperanca-solidaria-api:${{ steps.set_tag.outputs.tag }} ./src

      - name: Build Docker Image Worker
        run: docker build -f ./src/workers/EsperancaSolidaria.Worker.DoacaoRealizada/Dockerfile -t esperanca-solidaria-worker-doacao-realizada:${{ steps.set_tag.outputs.tag }} ./src